### ISSUE TITLE
Configuration level settings

### ISSUE THREAD

**Issue by rastographics** [tameraydin/ngToast#10]
Angular noob question, but I can't find this anywhere...
I studied the [page referred to on your site](https://docs.angularjs.org/guide/providers) for setting the global configuration of ngToast. With this code: 

``` javascript
angular.module('myModule').config(function(ngToast){
 ngToast.settings.horizontalPosition = 'center';
});
```

angular give me error "Unknown provider: ngToast"
(If i remove this configuration block, ngToast otherwise works great with my setup.)

I'm sure the problem is me, but could you tell me if there is anything glaringly wrong with my code?
Maybe a few samples lines of how to do the configuration would be very helpful on the site, too.

Thanks

**Comment by fervanrijswijk** [comment]
Hmmm, not working here. Using the exact same code gives me this error:

Error: [$injector:unpr] Unknown provider: ngToastProvider

**Comment by matt-jay** [comment]
I have the same issue as @fervanrijswijk.

In my Angular-Meteor app, I am trying

```
angular.module(...).
.config(config);

function config(..., $ngToastProvider) {
    'ngInject';

    $ngToastProvider.configure({
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      maxNumber: 3
    });
}
```

**Comment by tameraydin** [comment]
``$ngToastProvider`` -> ``ngToastProvider``
