### ISSUE TITLE
Event handlers in links inside toasts?

### ISSUE THREAD

**Issue by drothlis** [tameraydin/ngToast#14]
Hi there

I wonder if it's possible to have an `<a ng-click=...>` in the toast
content. For example: http://plnkr.co/edit/PmBFNugm9s0TlVLbpmx2?p=preview

It doesn't seem to work -- clicking on the link doesn't seem to call the
function as I'd expect. I've tried marking the `content` value with
`$sce.trustAsHtml` but it doesn't make any difference.

Any ideas?

Thanks for your time (and for ngToast!).

Dave.

**Comment by NPToita** [comment]
to accommodate drothlis 's requirement (which is also what i'm needing), I made for the following changes to ngToast itself:
1. in the provider - added the scopeToCompile property as part of the defaults object.
2. in the toast directive's compileContent check in the link function - add a var scopeToCompile = scope.message.scopeToCompile || scope.$parent and replace "scope.$parent" with scopeToCompile in the $compile() call.

then usage is as followed: 
var app = angular.module('myApp', ['ngToast']);
app.controller('myCtrl',['$scope','$sce', 'ngToast', function($scope, $sce, ngToast) {
  $scope.toast = function(){
    ngToast.create({content : $sce.trustAsHtml('a <a ng-click="toast2()">toast</a> message2'),
    compileContent: true,
    compileToScope: $scope,
    dismissOnClick: false,
    dismissButton: true
    });
  };
  
  $scope.toast2 = function(){
    ngToast.create({content: 'linked Toast'})
  }
}]);

**Comment by tameraydin** [comment]
now with [1.5.1](https://github.com/tameraydin/ngToast/releases/tag/1.5.1), ``compileContent`` can also take $scope object to bind. (as backward compatibility *boolean* values are still supported: ``true``  will use parent scope)

**Comment by taharedape** [comment]
Thanks so much @levithomason you saved me hours! i was wondering which the ng-click does not work within the same controller and only with factory function :/
