### ISSUE TITLE
How to use array of messages in ngToast ?

### ISSUE THREAD

**Issue by TejasCMehta** [tameraydin/ngToast#17]
I didnt find such example and also didnt find any doc related to usage, so sorry if I am not aware of such things.

I have response from API like below 

``` javascript
var res = {
  "success": false,
  "errors": [
    {
      "message": "Name required!"
    },
    {
      "message": "Email required!"
    }
  ]
}
```

Please let me know how to use such errors array with ngToast.
Thanks,

**Comment by drothlis** [comment]
It's up to you! If you want a single toast with all the error messages, call ngToast once and join the error messages together into a single string. If you want a separate toast for each error, then iterate over your errors array and call ngToast once for each message.

**Comment by TejasCMehta** [comment]
Thanks for reply... I did iteration on messages array and my work done :)
I wonder that I can show all error like <ul><li> format instead of each messages as single toast.If any sample than it will be big help.

thanks once again :+1:
