### ISSUE TITLE
Internet Explorer 8

### ISSUE THREAD

**Issue by cily** [tameraydin/ngToast#18]
Is this supposed to work in Internet Explorer 8? I noticed the recent commit "fixed IE8 reserved keyword error" and was a little hopeful that this would work in IE8, however when opening the demo page http://tameraydin.github.io/ngToast/ there are several script error pop-ups and clicking the "Create a sample toast" button does nothing.

**Comment by eknowles** [comment]
I'm fixing this to work in IE8 atm, I should have a PR soon.

**Comment by cily** [comment]
Awesome, glad to hear that.

**Comment by tameraydin** [comment]
Honestly haven't tested it with any version lower than 10 and have no intent for it. But any PR is welcomed! 

For reserved keyword fix, i knew that it would throw an error.

**Comment by eknowles** [comment]
Well my change is a bit of a breaking fix, it changes

`
defaults = { class: ... } 
`
to

`
defaults = { className: ... } 
`
So if people were using this is their projects they would all need to change over, not sure how the @tameraydin feels about that

**Comment by tameraydin** [comment]
Thanks for the PR, unfortunately have no any environment to test it on IE8. And no worries about property change, I will be mentioning that on release notes.

@cily can you confirm that you don't get the same error at [http://eknowles.com/test/](http://eknowles.com/test/) ?

**Comment by cily** [comment]
I don't see the same errors, but I was unable to get it to work in IE Tester or using the IE8 emulation in IE11. I do get one console error which is "TypeError: Object doesn't support property or method 'indexOf'". Unfortunately I don't have a true version of IE8 to test on either. My company used to have virtual machines with it installed and they kept auto-updating. IE Tester is fairly reliable but its "debugger" is pretty useless. I'm going to try this out and get back to you https://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by eknowles** [comment]
I use a VM, modern.ie I think it is

**Comment by tameraydin** [comment]
I see, what I think is we should have the fixes that @eknowles committed but just leave the rest to the user. For instance, in your case @cily, you can easily extend Object prototype to have an "indexOf" method. 

So thank you guys for your effort and feedback. Soon there will be a minor release for that along with another enhancement.

**Comment by tameraydin** [comment]
Closed with #19

**Comment by cily** [comment]
Apparently indexOf simply didn't exist in versions of IE before 9. perhaps we'll add a polyfill or something. Thanks for the updates!
