### ISSUE TITLE
Library works fine but logs constant "object is not a function" error

### ISSUE THREAD

**Issue by sodle** [tameraydin/ngToast#20]
![image](https://cloud.githubusercontent.com/assets/4439158/5883291/55e26dd6-a30e-11e4-801e-87a9f45bd7dd.png)

These errors appear constantly under Angular 1.3.x, though do not seem to affect page behavior.

**Comment by tameraydin** [comment]
can you please create a jsfiddle to demostrate that?

**Comment by sodle** [comment]
Nevermind. This was caused by Bower mistakenly downloading the wrong version of ngAnimate and ngSanitize for my version of Angular. Your latest bower.json appears to have solved the issue.

**Comment by tameraydin** [comment]
Fixed with #22
