### ISSUE TITLE
New Feature (?) Request: History

### ISSUE THREAD

**Issue by makzumi** [tameraydin/ngToast#21]
Hi tameraydin,

Thanks for making this, it's great!

Is there any way to get like the message history? would be handy in case someone wanted to go back and look at an activity log or something...
```
	ngToast.create({
		content: 'hello you ;) ',
 		history:true,
 		history_length:200
	});
	$scope.toasts = ngToast.getHistory();
 	// [{timestamp:1422085431719,message:'hello you ;0 '}] <<<$scope.toasts
```
Thanks!!

**Comment by makzumi** [comment]
Went through the code and found it, didnt see it in the docs. thanks :)

**Comment by makzumi** [comment]
well, not quite... after playing with it, messages are stored only while they are displayed...

**Comment by tameraydin** [comment]
Hi, as you noticed there is no such functionality to store and provide any toast history. 

It would be a nice feature though, but I think it is not good idea to keep all these info in ngToasts itself. What do you think about this; whenever a toast is created -and also on other events- ngToast would broadcast an event -named "ngToast:created", for instance- with all the information via rootScope, so you can listen that event wherever you want in your app? 

I think this will resolve your case and will also give the ability to track/record toast activities for user.

**Comment by makzumi** [comment]
Hey, thanks for the reply!
That would work too, having it dispatch an event, then i could store it or whatever...
In my local copy i added support for history, so that works for me right now, but if in a future release this gets implemented then all the better,

Thanks again!

**Comment by levithomason** [comment]
Hey guys, I had an idea that I think would solve the history case and not require adding events.

You could create a factory that had a history array and a thin wrapper around ngToast.  Since you must call ngToast.create() as is to create a toast you can at the same time add that toast data to the history array on your factory.

What do you guys think?

**Comment by tameraydin** [comment]
I agree, your solution sounds well. 

So I don't think that any implementation is necessary, let's keep it simple, lightweight and focused on what it does.

**Comment by levithomason** [comment]
Cool, glad we're on the same page. 

@makzumi let me know if you need anything further.  I'm willing to provide a plnkr and/or answer questions so as to not leave you hanging.

**Comment by makzumi** [comment]
Thanks guys!
Sounds like a great solution. @levithomason what I did locally, on my copy of it is the same thing, only no factory in my case. I just created a "private" var inside and add new messages to it, and pop out the rest when they reach the history length.
That way, it's kinda clean and I can limit history... Like in my original post...
I'll keep an eye out for this feature.
Thanks again guys!
