### ISSUE TITLE
Gulp?

### ISSUE THREAD

**Issue by levithomason** [tameraydin/ngToast#23]
What do you think about migrating to Gulp for the build?  I see you are using it on some other repos.

I have written many a gulpfile and could whip out a superb eqivelant gulpfile quickly.  Let me know if you would like to do this.  If yes, I'll add my build ideas to this issue before embarking.

**Comment by tameraydin** [comment]
I don't see any bad on it since it won't affect the end product but speed-up our build process, as long as providing same functionality.

**Comment by levithomason** [comment]
Great, if possible I first finish the animation options.  Then do gulp.  If I run into extra complications, I may do gulp in the animation branch.

**Comment by eknowles** [comment]
this would be fine as long as we keep the grunt :dash:

**Comment by tameraydin** [comment]
Yes, we should still keep gruntfile as it works now :+1: 
I think maybe we shouldn't even bother with implementing Gulp, since there -most probably- will be no any major enhancements in future.

**Comment by levithomason** [comment]
I agree. I opened this issue when I first started working on me animation branch. with that done and out of the way I don't think it makes sense to overhaul the build for no reason. Closing this issue then, thanks.

**Comment by levithomason** [comment]
Curious though what does that Grunt wind emoticon mean?
