### ISSUE TITLE
Update documentation on GitHub webpage : className instead of class

### ISSUE THREAD

**Issue by phearme** [tameraydin/ngToast#24]
Please update settings documentation on this page:
http://tamerayd.in/ngToast/#settings

property 'class' has been replaced by 'className'

**Comment by tameraydin** [comment]
When the new release is published, I will be doing that. Latest stable version ([1.3.0](https://github.com/tameraydin/ngToast/releases)) does not include this change.

**Comment by phearme** [comment]
Oups, alright then. Thanks for the great work. :)
