### ISSUE TITLE
Getting errors from ngTransclude

### ISSUE THREAD

**Issue by Kuzmin** [tameraydin/ngToast#26]
Hello! 

I am using this directive together with the oldest version of angular that you support (1.2.15), and I'm running into this error:

    Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <span ng-if="!message.compileContent" ng-transclude="" class="ng-scope">

I have tried debugging it a bit, but to no avail. Any idea as to why this might occur? A very big thank you for this super-useful library!

**Comment by tameraydin** [comment]
Could you please create a plunkr so I can also try to understand what might be cause? 

It sounds to me like a bug that is related to compileContent feature which is introduced at the latest version, but let's check ..And sorry, unfortunately we haven't enough tests to cover all functionalities yet :(

**Comment by tameraydin** [comment]
Hey @Kuzmin have you managed to solve this issue?

**Comment by EsraAkyurt** [comment]
"angular-1.2.9/angular.js"  // Getting this error when used. 
<script data-require="angular.js@1.4.0-beta.6" data-semver="1.4.0-beta.6" src="https://code.angularjs.org/1.4.0-beta.6/angular.js"></script> //this version does not get an error when used.
