### ISSUE TITLE
update the doc property 'className:' is changed to 'class:'

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [tameraydin/ngToast#28]
so use class in place of className 
for eg. ngToast.create({class:'info',content:'This is an info type alert!',dismissButton:'true'});

**Comment by tameraydin** [comment]
``class`` has changed to ``className`` with version [1.4.0](https://github.com/tameraydin/ngToast/releases/tag/1.4.0). You probably use a lower version than the latest, I recommend you to update it.
