### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by mastermind1981** [tameraydin/ngToast#33]
Hi,

First of all, I want to thank you for your great job.

I want to experience ngToast but it seems not working.

I created an example with the code grabbed from the demo page.

Here is the [plunker] (http://plnkr.co/edit/QqIjn682rnFCV4rXkLib), may be i'm missing something!!

Thank you

**Comment by levithomason** [comment]
Working fork [here](http://plnkr.co/edit/zu3l7QGUPEWAVbFGIchF?p=preview).

There were a number of problems with both the example and the ngToast package on plunker:

Your example issues:
1) `ng-app` directive cannot be on the `<head>` tag.  Moved to the `<html>` tag.
2) Scripts were loaded in the wrong order.  Angular and it's dependencies must be loaded before ngToast.  (Note, load order is not guaranteed in the browser).
3) Angular Sanitize is an ngToast dependency and was missing.

@tameraydin are we managing the plnkr package? There are some issues:

1) It is trying to load resources directly from GitHub.  GitHub doesn't allow that, the MIME types are wrong and hence nothing is loading.  The URLS patterns need changed from:
`https://github.com/tameraydin/ngToast/blob/master/dist/ngToast.css`
to:
`//rawgit.com/tameraydin/ngToast/1.4.0/dist/ngToast.css`

2) The version number needs updated to 1.5.0.

I've not added packages on plnkr so I'm not sure how that is fixed.  Let me know what you'd like to do there.  Thanks.

**Comment by mastermind1981** [comment]
Got it Thank you very much

**Comment by levithomason** [comment]
Great, you are very welcome.

**Comment by tameraydin** [comment]
Hey @levithomason, I don't often use plunker so have no idea about how to make these updates, feel free to update.

Just curious, how do we create/maintain a package on it, and is there any existing package for ngToast?

**Comment by levithomason** [comment]
The only way I know is to add a package in plnkr.co itself, or click on it's name and hit edit.  I'll see if I can do this and report back.  Also, moving to a separate issue for this.
