### ISSUE TITLE
Plunker package is not working

### ISSUE THREAD

**Issue by levithomason** [tameraydin/ngToast#34]
This issue picks up the plunker package work from #33.

- [x] fix bad urls in v1.4.0
- [x] include all dependencies for 1.4.0
- [x] add bootstrap css only for 1.4.0 (so we don't also need jQuery)
- [x] add 1.5.0 package

**Comment by levithomason** [comment]
Well, plunker went down mid updating :).  I'll finish this up later.

**Comment by levithomason** [comment]
Alright, I've updated the version 1.4.0 package and deps to be correct.  I also added the version 1.5.0 package.  We're all set now for happy plnkr's.

**Comment by tameraydin** [comment]
great :+1:
