### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by blair55** [tameraydin/ngToast#40]
I've scaffolded a yoeman angular app with the minimum necessary to show a toast - but it doesn't!

This is my repo: https://github.com/blair55/toasttest

I thought it could be a versioning problem as per other issues but this bower.json seems fine according to your docs.

````
...
  "dependencies": {
    "angular": "^1.3.0",
    "angular-route": "^1.3.0",
    "ngtoast": "~1.5.0"
  }
...
````

To recreate, please clone, `grunt build`, `grunt serve` then follow the Show Toast link.

**Comment by tameraydin** [comment]
I don't see any ``<toast>`` element in your HTML. This must be the reason.

**Comment by blair55** [comment]
True, but your docs say:

> Place toast (or ng-toast, if you are using a version lower than 1.2.1) element into your HTML

**Comment by blair55** [comment]
My bad, I mis-read that as `<toast>` or `<ng-toast>` is only required if on a version lower than 1.2.1. Thanks for your help.

**Comment by tameraydin** [comment]
np!
