### ISSUE TITLE
Controller/ControllerAs/TemplateUrl options

### ISSUE THREAD

**Issue by zooofeex** [tameraydin/ngToast#41]
Hi, 
it would be great to have an option for associating a controller with a toast.

```js
//for example
var aToast = ngToast.create({
  className: 'warning',
  content: 'Another message as <a href="#" class="">HTML</a>',
  controller: 'StringOrFunction',
  controllerAs: 'ctrl'
});
```

Also an option for setting `templateUrl` would be nice, for auto loading and compiling the content.

Do you plan to implement this?

**Comment by levithomason** [comment]
Hi @zoofeex, there may be a way to accomplish this. What is your use case?

**Comment by tameraydin** [comment]
Hi, picking up controller by name is bit tricky imho and not sure if it is a right approach, so no any plans to implement such a feature. but any PRs with tests are welcome of course.
