### ISSUE TITLE
Pause timeout

### ISSUE THREAD

**Issue by bradyclifford** [tameraydin/ngToast#47]
When a user hover's over the toast, it would be nice if it paused its timeout countdown.  This is a feature that AngularJS-Toaster utilizes.  Could this be implemented?

**Comment by levithomason** [comment]
@tameraydin this is something I also wanted, making it 3 folks to request so far. 

If you agree, mark it for implementation and I'll knock it out soon.

**Comment by tameraydin** [comment]
I agree, let's implement this then.. Probably we would introduce an optional boolean parameter like ``resetTimeoutOnMouseover`` for that.

**Comment by bradyclifford** [comment]
That would be perfect.

**Comment by rictorres** [comment]
:+1: sounds good!

**Comment by tameraydin** [comment]
hey @levithomason will you be handling this? I was thinking to release a minor version update along with #48 once we implement this one.

**Comment by levithomason** [comment]
that is my intent, however, I'll be traveling all next week and would not be able to get to this until later the following week.

 feel free to knock it out if you have time otherwise I'll get to it after a while.

**Comment by levithomason** [comment]
See #51

**Comment by tameraydin** [comment]
Thx guys, it is available with [1.5.3](https://github.com/tameraydin/ngToast/releases/tag/1.5.3)

**Comment by jannickfahlbusch** [comment]
How can we instruct ngToast to do this?

I didn't found anything regarding this in the docs.

**Comment by tameraydin** [comment]
This functionality added as default, so you don't have to instruct or set any option. 
(Eventually it is applied only if ``dismissOnTimeout`` is enabled.)
