### ISSUE TITLE
Toast Strange Behaviour

### ISSUE THREAD

**Issue by agustincba** [tameraydin/ngToast#52]
Hi !. My problem is the folowing... I am using bootstrap and angular; to be more precise... The modal plugin... The problem I have arises when I try to creat a toast... Because only the text appears and sometimes it's all ok... I thought it didnt work but I could managento see the text... I cant make a plunker but be sure I'll be uploading a pic... Thanks

**Comment by tameraydin** [comment]
If the text appears but not the toast, sounds like an CSS issue, there might be some overriden rules... It would be very difficult to understand & help without seeing any code.

**Comment by agustincba** [comment]
Hi Tameraydin !. Here are some pics about this issue... I leave this link:
http://cholordoweb.com/code.zip
Where you will be able to download php page and the js from the angular logic... Hope it helps !. Thankx ! :D

![foto_nro_01194](https://cloud.githubusercontent.com/assets/654436/7939236/c8f60930-08fe-11e5-8af9-09f706a7e87e.jpg)
![foto_nro_01195](https://cloud.githubusercontent.com/assets/654436/7939243/d403e7fc-08fe-11e5-9b8c-17ad81f47a53.jpg)

**Comment by tameraydin** [comment]
Seems ngToast works properly. You should inspect the element on DevTools and see what kind of CSS rules overrides the ones from ngToast and fix accordingly.

**Comment by agustincba** [comment]
Mmm... Perfect... I will check that !... Let me see... Thankx

**Comment by agustincba** [comment]
Now is working Ok tameraydin... I was thinking about this... And I came to this conclusion: If you checked my angular script, I made a function with two params in order to make use of your toasts... The thing is that the second param didn't have a correct value considering "success", "info", "warning" or "danger". I put for example "error" instead and I could recreate the issue... THANKX again for the attention... The problem in brief was the param...

**Comment by tameraydin** [comment]
great! you're welcome
