### ISSUE TITLE
angular 1.4 support

### ISSUE THREAD

**Issue by bdwain** [tameraydin/ngToast#53]
It's unclear if this supports angular 1.4 or not right now. The bower dependency says <= 1.4.0, but that means 1.4.0 is a valid version. If angular 1.4 is supported, can the dependency be changed to something like < 1.5 ?

**Comment by tameraydin** [comment]
You're right, if it is working fine with 1.4, minor versions shouldn't cause any issues.. I will update it asap. 
Thanks

**Comment by bdwain** [comment]
now that this is out would it be possible to bump the version of this to 1.5.4?

**Comment by tameraydin** [comment]
done [1.5.4](https://github.com/tameraydin/ngToast/releases/tag/1.5.4). thanks for the PR!
