### ISSUE TITLE
Hover should respect dismissOnTimeout preferences

### ISSUE THREAD

**Issue by nathand8** [tameraydin/ngToast#56]
First of all, ng-toast is beautiful. Thanks to anyone who contributes.

Here's my problem: In the configuration, I set dismissOnTimeout to false. It's respected except when you drag your mouse over it. After the mouse leaves, the timeout is started and it disappears when the timeout finishes

**Comment by tameraydin** [comment]
sorry for the late response...

good catch! -again feeling the lack of tests here :(- 
I will release a version update asap.

**Comment by tameraydin** [comment]
Available on [1.5.5](https://github.com/tameraydin/ngToast/releases/tag/1.5.5)
