### ISSUE TITLE
Can you use multiple configurations for ngToast?

### ISSUE THREAD

**Issue by inclusiv1** [tameraydin/ngToast#58]
I have an application where I am utilizing ngToast.  In a modal I want the animation to be slide down from the top:
```ngToast.configure({
			animation: 'slide',
			verticalPosition: 'top',
			horizontalPosition: 'center'
});
```
but for the page notifications I just want it to slide in from the right (default slide animation).
If I create two different configurations, I see that they all get the same thing, basically all the notifications will slide down, centered on the page fromt the top.

**Comment by inclusiv1** [comment]
I forgot the singleton aspect of a provider... I will figure out another method in which I can do it.

**Comment by tameraydin** [comment]
Hi @inclusiv1 yes probably it won't possible to have multiple configurations.. But I think you can achieve this by CSS only, by writing some custom animations (or just copy the built-in ones) and using a parent selector + you can use ``additionalClasses`` to add your custom classes if needed. 

Check out the example here, might be helpful: #32
