### ISSUE TITLE
Animation Options

### ISSUE THREAD

**Issue by levithomason** [tameraydin/ngToast#6]
**On/Off**
Currently ngToast provides css animations by default.  How do you feel about making this optional?  This way if users want to use their own animations with ngAnimate they won't have to override the built in animations css.

**Type**
We could include a couple other animation types such as:
* SlideInOut: Slides into the browser on show, and slides out on hide.
* Flip: 3d flip into view, flip out of view (like a card).
* etc

It'd also be nice to use 3d transforms so we get the hardware acceleration.

Does this fit in your vision for this modules future?

**Comment by davincho** [comment]
Maybe you could use all animations provided by animate.css (http://daneden.github.io/animate.css/) and integrate them.

**Comment by levithomason** [comment]
Nice!  That was my first thought with this as well.  I had alot of thoughts this.  There are a number of well known options for animations:

[Animate.css](http://daneden.github.io/animate.css/) (as you mentioned)
[ngFx](https://hendrixer.github.io/)
[TweenMax](http://greensock.com/) (super performant, even on mobile)
[Velocity.js](http://julian.com/research/velocity/)
...and others

I was hesitant about much animation responsibility to pack into ngToast.  On one end of the spectrum we could go really deep and have lots of animations and options like speed, easing, callbacks, etc.  On the other end (perhaps where it is going) is very minimal animations with no third party dependencies.

I wasn't 100% resolved, but went with a lighter build.  Let's find out what @tameraydin thinks, too.

Tamer,  what is your vision for animation support in ngToast?

**Comment by davincho** [comment]
Taking as an example Animate.css: We would only need one additional attribute such as `className` for styling the ngToast, let's say `animationClass`. Backwards compatibility with Animate.css could be an issue though (http://caniuse.com/#feat=css-animation).

**Comment by levithomason** [comment]
I really like the animation class idea. If done well, one could potentially use the animation class option as a way to trigger animations with any animation library, including their own custom animations.

I'll test this idea out and create a plnkr soon.  Thanks again!

**Comment by tameraydin** [comment]
Hopefully, with these upcoming new [animation options](https://github.com/tameraydin/ngToast/pull/29), it will be very easy to add -at least few basic types of- animations into ngToast, and it will also provide a CSS animation base to refer for those who may want to enhance or use different type of animations. So I think, adding more than that, would a bit much responsibility for ngToast.

**Comment by tameraydin** [comment]
Closed with #29
