### ISSUE TITLE
Unable to configure sass variables

### ISSUE THREAD

**Issue by ysavary** [tameraydin/ngToast#61]
Hello,

Thank you for this project ! I'm trying to configure my toasts position by adding a vertical offset:

**1. I cannot customize sass variables because $ngt-spacing is already set in variables.scss.** 
I discovered that using !default in ng-toast/src/styles/sass/variables.scss as following:
```scss
$ngt-spacing: 20px !default;
$ngt-transition-duration: 0.3s !default;
$ngt-transition-timing-function: ease !default;
```
allows me to put in my scss file:
```scss
$ngt-spacing: 50px;
@import "ngToast";
```

**2. I would like to have an horizontal and a vertical spacing like**:
 ```scss
$ngt-horizontal-spacing: 20px !default;
$ngt-vertical-spacing: 20px !default;
```

**Comment by tameraydin** [comment]
Hi @ysavary, you can override this value in your application's CSS, like:
```css
.ng-toast { margin-top: 30px; }
```
It is not good practise to customise 3rd party libs in your app, imho.

**Comment by ysavary** [comment]
@tameraydin Of course... thank you for your response
