### ISSUE TITLE
angular.module('aModule', [..., require('ng-toast')]) raises an error

### ISSUE THREAD

**Issue by ysavary** [tameraydin/ngToast#62]
This syntax will raise an error:
``` javascript
angular.module('aModule', [..., require('ng-toast')])
```

Unlike some others modules (angular-sanitize, angular-ui-router, ..), I must use the following syntax:
```javascript
require('ng-toast');
angular.module('aModule', [..., 'ngToast'])
```

**Comment by tameraydin** [comment]
I don't think ng-toast module has anything to do with this issue..
