### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Jozef2** [tameraydin/ngToast#65]
Hi guys,

thank you for wonderful project. Do you have any plans to support [nuget packages](https://www.nuget.org/) for Visual Studio developers?

Jozef

**Comment by tameraydin** [comment]
Hey @Jozef2, thanks for your nice words! 

Frankly, I haven't used it anytime before and there is no any future plans to support it. But -if you think that is possible at all and feasible- feel free to register a mirror repo that contains distribution files of ngToast.
