### ISSUE TITLE
Custom template in separate file

### ISSUE THREAD

**Issue by SET001** [tameraydin/ngToast#68]
I can change default message template by using 

    <toast template="popup.html"></toast>

and  placing it's template before `toaster` directive

    <script type="text/ng-template" id="templateId.html"> 

so it will rewrite defaults in `$templateCache`. But how can I have this template in separate file? If I try to load it in `run` block like this:

    $templateRequest('views/popup.html').then(function (response) {
            $templateCache.put('popup.html', response);
    });

it will not work because  directives compile will run before $templateRequest will resolved

So how can I have template in separate file?

**Comment by yofreke** [comment]
Added template support for a project of mine.  Pull request https://github.com/tameraydin/ngToast/pull/77 is open, but hopefully my fork will help you out until then d:

**Comment by moravcik** [comment]
I have done this using `$templateRequest` and `$sce`:

    var toastScope = $scope.$new(true);
    // setup desired parameters on toastScope
    $templateRequest(/*path to your template*/).then(function(html) {
        ngToast.warning({
            content: $sce.trustAsHtml(html),
            compileContent: toastScope
        });					
    });

However, I think custom templateUrl might be supported by default as it is a standard way of defining templates in UI router and Angular directives as well.
