### ISSUE TITLE
Remove ngAnimate from Bower dependencies?

### ISSUE THREAD

**Issue by bradleyflood** [tameraydin/ngToast#69]
Considering `ngAnimate` is optional it would be nice if this was not a Bower dependency.

In my situation I am not using the animate feature, yet Bower is downloading the `angular-animate` package with `ngToast` due to its dependent state, and my build system which imports all my Bower files then needlessly imports `ngAnimate`.

I think that `angular-animate` should be remove from the `bower.json` `dependencies` as it is not critical or required for ngToast to run. It's optional.

Of course I could hard-code an exclusion into my build process but would prefer not to have too many hard coded exceptions.

Anyway what are your thoughts?

Cheers,
Brad

**Comment by tameraydin** [comment]
Sorry for the late reply.
Actually I agree, it is obviously not a dependency but I am bit concerned about backward compatibility. To ensure that it is, a major version bump (v2) is necessary and that what makes me hesitate..
