### ISSUE TITLE
'fade' animation option does not working

### ISSUE THREAD

**Issue by aebmknrl** [tameraydin/ngToast#74]
I put this conf:

`.config(['ngToastProvider', function(ngToast) {
    ngToast.configure({
      horizontalPosition: 'center',
      maxNumber: 1,
      animation: 'fade',
      dismissButton : true
    });
  }])`

And a service:

`.service('ShowErrorMessages',['$rootScope','ngToast', function($rootScope,ngToast){
		this.ShowErrorMessage = function(message){
			  var myToastMsg = ngToast.danger({
			  content: message
			});
		}
	}])`

All the options are working as is spected, but the "animation" does not. This are my definitions on html:

    <link rel="stylesheet" href="css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="css/main.css" />
    <link rel="stylesheet" href="css/angular-busy.min.css" />
    <link rel="stylesheet" href="css/ngToast.min.css">
    <link rel="stylesheet" href="css/ngToast-animations.min.css">
    <script src="js/jquery-1.12.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/angular.min.js"></script>
    <script src="js/solempApp.js"></script>
    <script src="js/messages.js"></script>
    <script src="js/angular-ui-router.min.js"></script>
    <script src="js/showErrors.min.js"></script>
    <script src="js/angular-local-storage.min.js"></script>
    <script src="js/angular-busy.min.js"></script>
    <script src="js/angular-animate.min.js"></script>
    <script src="js/angular-sanitize.js"></script>
    <script src="js/ngToast.min.js"></script>

Thanks for the excellent work on this plugin.

**Comment by tameraydin** [comment]
Can you please provide a fiddle/plunkr with the issue?

**Comment by chrilehner90** [comment]
Did you inject ngAnimate into your app?

Something like this:
```coffee
app = angular.module "app", [
    "ngToast"
    "ngAnimate"
]
```
