### ISSUE TITLE
After reading the same file twice the toast message appears only the first time

### ISSUE THREAD

**Issue by chrilehner90** [tameraydin/ngToast#76]
Hi,

I am trying to show toast messages inside a change callback of a file input field.
It works perfectly in Firefox but in Chrome the toast message appears only the first time when the user selects the same file twice.

I made a little plunkr:
[http://plnkr.co/edit/EcPdlNcLRCzVYWWL1xFY?p=preview](http://plnkr.co/edit/EcPdlNcLRCzVYWWL1xFY?p=preview)

Is this a bug in ngToast or something of Google Chrome?

Thanks in advance!

**Comment by tameraydin** [comment]
Hi @chrilehner90, it seems like a Chrome specific issue:
http://stackoverflow.com/questions/10214947/upload-files-using-input-type-file-field-with-change-event-not-always-firin
http://stackoverflow.com/questions/6623310/input-file-onchange-event-not-being-fired-in-chrome

**Comment by chrilehner90** [comment]
you're right. I didn't see these ones earlier. thank you!
