### ISSUE TITLE
Update dependency versions on bower.json

### ISSUE THREAD

**Issue by bertonha** [tameraydin/ngToast#79]

**Comment by samarthagarwal** [comment]
Not working with Angular 1.4.9 as well for me.

**Comment by tameraydin** [comment]
@samarthagarwal can you create a plunkr?

**Comment by samarthagarwal** [comment]
My live demo is here https://angularjs-samarthagarwal.c9users.io/#/signup

**Comment by tameraydin** [comment]
I did a basic test with 1.5 and seems like it works, can you please provide a plunkr?

**Comment by bertonha** [comment]
My primary problem is the dependency restriction on bower.json
```
"angular": ">=1.2.15 <1.5",
```
https://github.com/tameraydin/ngToast/blob/master/bower.json#L27-L29

**Comment by tameraydin** [comment]
Ok I see. I am going to release another version anytime soon, which will be addressing also that.

**Comment by timc13** [comment]
+1

**Comment by tameraydin** [comment]
Please use version [2.0.0](https://github.com/tameraydin/ngToast/releases/tag/2.0.0)
