### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by TeChn4K** [tameraydin/ngToast#80]
Hi,
Many thanks for your work !

There is a typo in the ngToast documentation : `dismissButton` default is `true`, not `false` ;)

**Comment by tameraydin** [comment]
Seems correct, the default is ``false``:
- https://github.com/tameraydin/ngToast/blob/master/src/scripts/provider.js#L16
- http://tamerayd.in/ngToast/

**Comment by TeChn4K** [comment]
My bad sorry. I double check my conf and the documentation is correct indeed.
