### ISSUE TITLE
'slide' Animation not sliding in

### ISSUE THREAD

**Issue by jayrav13** [tameraydin/ngToast#85]
I downloaded ngToast v2.0.0 from bower and first off, this library is awesome! I'm interested in the slide animation.

Expected: basically mimic iOS Push Notifications, where the notification slides in from the right and then slides back out.

Actual: The background of the animation pops up in it's final location at the beginning of the animation and the text slides into it from the right. 

Just wondering if this is expected behavior or a bug? Any help is appreciated!

**Comment by jayrav13** [comment]
Note - one of the reasons I ask is because the slide out portion is exactly as expected. Thanks again!

**Comment by jayrav13** [comment]
Ah - an update, this only happens on a notification is fired off on page load. Any subsequent notification (which I hadn't seen come in yet) is as expected. Just something to look into if interested.

Thanks!

**Comment by tameraydin** [comment]
Can you please provide a plunker/jsfiddle where I can see what is happening? (It might be related to your CSS/JS codebase)
